### ISSUE TITLE
Not enough examples on how to use

### ISSUE THREAD

**Issue by joevandyk** [blackwinter/cmess#2]
For example, I have no idea on how to use the Cinderella module.

**Comment by blackwinter** [comment]
Hi Joe,

thank you for your interest in this project. I'm not exactly sure what kind of information would be beneficiary to your request, but there are example files provided for `cinderella`; change into the `example/cinderella` directory and run the following commands to reproduce them:

- `cinderella -i empty6-slash.txt -p pot -c crop -e iso-8859-1`
- `cinderella -i empty6-slash.txt -c crop_repaired -r -e iso-8859-1`
- `cinderella -i empty6-slash.txt -o empty6-slash_repaired.txt -r -e iso-8859-1`

Please note that I haven't given this project any attention for a long time. In writing this answer I stumbled upon a few errors that I had to correct and released as version [0.5.1](https://rubygems.org/gems/cmess/versions/0.5.1).

If you have any more questions, please don't hesitate to ask.

Cheers,
Jens
